name: 🚀 Deploy to Shopify (Fitz Frenzy)

on:
  push:
    branches:
      - fitz-frenzy  # deploy only from this branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 📦 Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: 🚀 Deploy theme to Shopify
        env:
          SHOPIFY_FLAG_STORE: su6i35-7c.myshopify.com
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.GETHUBDEPLOY }}
        run: |
          shopify theme push --path . --unpublished
